# basic options, this hash is nota  markdown because we ar in yaml
title: MUSICATIKITAKA-BLOG
author: AOP
email: your-email@domain.com
description: MusicaTikitaka es una página didáctica 
github_username:  aelmoo

# Build settings
markdown: kramdown
theme: minima
